line.bot:
  channel-token: 'z7et9mVglJCAt7Z8hAhxpgNGBDyjh7iYE0Vy3R4HeHA7ZefF/dsWYWNJ1itdPN+rbgW7iig65DrYcgHV/5tc0wWeqiQ9qKX+2YU/QzyD2/hLLRhpK9mnNrsRpWfB5+wZciQEJ8sg6am3rM/BtWf+WwdB04t89/1O/w1cDnyilFU='
  channel-secret: 'a614a69ea661b01c0b8e97a20df9fd13'
  handler.path: /callback
